== Additional recommended steps

We recommend that, when deploying {zotLowerName}, you also install the command
line (<<#_zli_chapter, zli>>) and benchmarking (<<#_zb_chapter, zb>>) packages.

== Launching {zotLowerName}

NOTE: The instructions and examples in this guide use `zot` as the name of the
{zotLowerName} executable file and do not include the path to the
executable file.

The {zotLowerName} service is initiated with the `zot serve` command followed by
the name of a configuration file.

The configuration file is a JSON or YAML file that contains all configuration
settings for {zotLowerName} functions. Using the information in this guide, you
can compose a configuration file with the settings and features you require for
your {zotLowerName} registry server.

TIP: Before launching {zotLowerName}, you can check your configuration file
for errors or conflicts using the procedure described in
<<#_verifying_config, Verifying the configuration file>>.

When ready, you can launch {zotLowerName} using the following command:

``*zot* *serve* _configfile_``
