== CNCF Community Code of Conduct v1.1

Other languages available: -
xref:code-of-conduct-languages/ar.adoc[Arabic/العربية] -
xref:code-of-conduct-languages/bg.adoc[Bulgarian/Български] -
xref:code-of-conduct-languages/zh.adoc[Chinese/中文] -
xref:code-of-conduct-languages/cs.adoc[Czech/Česky] -
xref:code-of-conduct-languages/fa.adoc[Farsi/فارسی] -
xref:code-of-conduct-languages/fr.adoc[French/Français] -
xref:code-of-conduct-languages/de.adoc[German/Deutsch] - xref:code-of-conduct-languages/id.adoc[Indonesian/Bahasa
Indonesia] -
xref:code-of-conduct-languages/it.adoc[Italian/Italiano] -
xref:code-of-conduct-languages/jp.adoc[Japanese/日本語] -
xref:code-of-conduct-languages/ko.adoc[Korean/한국어] -
xref:code-of-conduct-languages/pl.adoc[Polish/Polski] -
xref:code-of-conduct-languages/pt.adoc[Portuguese/Português] -
xref:code-of-conduct-languages/ru.adoc[Russian/Русский] -
xref:code-of-conduct-languages/es.adoc[Spanish/Español] -
xref:code-of-conduct-languages/tr.adoc[Turkish/Türkçe] -
xref:code-of-conduct-languages/uk.adoc[Ukrainian/Українська] -
xref:code-of-conduct-languages/vi.adoc[Vietnamese/Tiếng Việt]

=== Contributor Code of Conduct

As contributors and maintainers in the CNCF community, and in the
interest of fostering an open and welcoming community, we pledge to
respect all people who contribute through reporting issues, posting
feature requests, updating documentation, submitting pull requests or
patches, and other activities.

We are committed to making participation in the CNCF community a
harassment-free experience for everyone, regardless of level of
experience, gender, gender identity and expression, sexual orientation,
disability, personal appearance, body size, race, ethnicity, age,
religion, or nationality.

== Scope

This code of conduct applies both within project spaces and in public
spaces when an individual is representing the project or its community.

=== CNCF Events

CNCF events, or events run by the Linux Foundation with professional
events staff, are governed by the Linux Foundation https://events.linuxfoundation.org/code-of-conduct/[Events Code of
Conduct] available
on the event page. This is designed to be used iconjunction with the
CNCF Code of Conduct.

== Our Standards

Examples of behavior that contributes to a positive environment include:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints, and experiences
* Giving and gracefully accepting constructive feedback
* Accepting responsibility and apologizing to those affected by our
mistakes, and learning from the experience
* Focusing on what is best not just for us as individuals, but for the
overall community

Examples of unacceptable behavior include:

* The use of sexualized language or imagery, and sexual attention or
advances of any kind
* Trolling, insulting or derogatory comments, and personal or
political attacks
* Public or private harassment
* Publishing others`' private information, such as a physical or email
address, without their explicit permission
* Other conduct which could reasonably be considered inappropriate in
a professional setting

Project maintainers have the right and responsibility to remove, edit,
or reject comments, commits, code, wiki edits, issues, and other
contributions that are not aligned to this Code of Conduct. By adopting
this Code of Conduct, project maintainers commit themselves to fairly
and consistently applying these principles to every aspect of managing
this project. Project maintainers who do not follow or enforce the Code
of Conduct may be permanently removed from the project team.

== Reporting

For incidents occuring in the Kubernetes community, contact the
https://git.k8s.io/community/committee-code-of-conduct[Kubernetes Code of Conduct
Committee] via
link:mailto:conduct@kubernetes.io[conduct@kubernetes.io]. You can expect a response within three business
days.

For other projects, please contact the CNCF staff via link:mailto:conduct@cncf.io[conduct@cncf.io].
You can expect a response within three business days.

In matters that require an outside mediator, CNCF has retained Mishi
Choudhary (mishi\@linux.com). Use of an outside mediator can be
requested when reporting or used at CNCF staff's discretion. In general,
contacting link:mailto:conduct@cncf.io[conduct@cncf.io] directly is preferred.

== Enforcement

The Kubernetes project's https://github.com/kubernetes/community/tree/master/committee-code-of-conduct[Code of Conduct
Committee]
enforces code of conduct issues. For all other projects, the CNCF
enforces code of conduct issues.

Both bodies try to resolve incidents without punishment, but may remove
people from the project or CNCF communities at their discretion.

== Acknowledgements

This Code of Conduct is adapted from the Contributor Covenant
(http://contributor-covenant.org), version 2.0 available at
http://contributor-covenant.org/version/2/0/code_of_conduct/
