= Zot Developer Guide
:doctype: book
:icons: font
:toc: left
:toclevels: 2

== Getting Started

=== Supported Developer Platforms

Development is officially supported on `Linux` and `Apple MacOS` platforms. However,
development should be possible on any platform that supports the `golang` toolchain.

=== Prerequisites

==== Install golang (1.17+)

The zot project requires `golang 1.17` or newer. You can follow
https://go.dev/learn/[these instructions] to install the `golang` toolchain.  After
installation, make sure that the `path` environment variable or your IDE can find
the toolchain.

=== Cloning zot

The zot registry code base is hosted on GitHub at https://github.com/project-zot/zot[https://github.com/project-zot/zot].

To clone the zot project, use this command:

----
$ git clone https://github.com/project-zot/zot.git
----

=== Building zot

To build zot, execute the `make` command in the zot directory using the
following general syntax:

``$ make OS=_os_ ARCH=_architecture_ {binary | binary-minimal}``

The `binary` option builds the full zot binary with all extensions. +
The `binary-minimal` option builds the minimal zot binary without extensions.

==== Examples

The following are examples of the `make` command for several supported platforms
and architectures:

- Linux/Intel-based platforms
+
----
$ make OS=linux ARCH=amd64 binary
----

- Linux/amd64 platform
+
----
$ make OS=linux ARCH=amd64 binary
----

- Linux/ARM64-based platforms such as ARM64 servers and Raspberry Pi4
+
----
$ make OS=linux ARCH=arm64 binary
----

- Apple MacOS/Intel-based platforms
+
----
$ make OS=darwin ARCH=amd64 binary
----

- Apple MacOS/ARM64-based platforms
+
----
$ make OS=darwin ARCH=arm64 binary
----

=== Running zot

The behavior of zot is controlled via configuration only.
To launch the zot server, execute the following command:

----
$  bin/zot-linux-amd64 serve examples/config-example.json
----


== Code Organization

The `zot` project codebase is organized as follows:

----
/
- pkg/              # Source code for all libraries
  - api/            # Source code for HTTP APIs
    - config/       # Global configuration model
  - storage/        # Source code for storage backends
  - cli/            # Source code for command line interface (cli)
  - common/         # Source code for common utility routines
  - compliance/     # Source code for dist-spec conformance tests
  - log/            # Source code for logging framework
  - test/           # Internal test scripts/data
  - extensions/     # Source code for all extensions
    - config/
    - sync/
    - monitoring/
    - sync/
  - exporter/       # Source code for metrics exporter
- cmd/              # Source code for binary main()s
  - zot/            # Source code for zot binary
  - zli/            # Source code for zot cli
  - zb/             # Source code for zb which is the dist-spec benchmarking tool
- errors/           # Source code for error codes
- examples/         # Configuration examples
- swagger/          # Swagger integration
- docs/             # Documentation
----


== Contributor Guidelines

=== License

zot is released under the
https://github.com/project-zot/zot/blob/main/LICENSE[Apache License 2.0].
All contributions must adhere to this license.

=== Developer Certificate of Origin (DCO)

All commits require a Developer Certificate of Origin via the "Signed-off-by:"
commit message and commit signatures using GPG keys.

=== Submitting a Pull Request (PR)

First, fork the zot project on GitHub and submit a commit to your fork.
Then open a new pull request (PR) to the zot project.

=== PR Requirements

Any new PR requires a form to be filled out with details about the PR.
Appropriate code owners are automatically identified, and they will be notified
of the new PR.

=== CI/CD Checks

We take code quality very very seriously. All PRs must pass various CI/CD
checks which cover enforce code quality such as code coverage, security
scanning, performance regressions, distribution spec conformance, ecosystem
client tool compatibility, etc.

== Reporting Issues

Issues are broadly classified as functional bugs and security issues. The
latter is treated a little differently due to the sensitive nature.

=== Filing an Issue

No software is perfect, and we expect users to find issues with the zot code
base. First, check whether your issue has already been filed by someone else by doing an
https://github.com/project-zot/zot/issues[issue search]. If the issue not found,
file a new issue by clicking the *New issue* button on the *zot/issues* page
and answering the questions. The more information that you can provide, the
easier it becomes to triage the issue.

=== Security Issues

Security issues are best filed by sending an email to `security@zotregistry.io.`
After 45 days, we will make the issue public and give credit to the original
filer of the issue.

== Code of Conduct

The zot project follows the
https://github.com/cncf/foundation/blob/main/code-of-conduct.md[CNCF Code of Conduct].

:leveloffset: +1

include::code-of-conduct.adoc[]

:leveloffset: -1

=== Reporting

For incidents occurring on the zot project, contact the zot project conduct
committee at `conduct@zotproject.io.` You can expect a response within three
business days.

== Notices

The documentation set for this product strives to use bias-free language. For the
purposes of this documentation set, bias-free is defined as language that does
not imply discrimination based on age, disability, gender, racial identity, ethnic
identity, sexual orientation, socioeconomic status, and intersectionality.
Exceptions may be present in the documentation due to language that is hardcoded
in the user interfaces of the product software, language used based on RFP
documentation, or language that is used by a referenced third-party product.
