== Common tasks with skopeo

https://github.com/containers/skopeo[`skopeo`] is a command line
client that performs various operations on OCI container images and image repositories.

NOTE: For detailed information about using skopeo, see the https://github.com/containers/skopeo/blob/main/docs/skopeo.1.md[skopeo man page]. 

=== Push an OCI image

This example pushes the latest container image for the `busybox` application to a zot registry.

----
$ skopeo --insecure-policy copy --dest-tls-verify=false --multi-arch=all \
   --format=oci docker://busybox:latest \
   docker://myZotRegistry.com:5000/busybox:latest
----

=== Pull an OCI image

This example pulls the latest container image for the `busybox` application and stores the image to a local OCI-layout directory (`/oci/images`).

----
$ skopeo --insecure-policy copy --src-tls-verify=false --multi-arch=all \
   docker://myZotRegistry.com:5000/busybox:latest \
   oci:/oci/images:busybox:latest
----

=== Pull an OCI image to a private docker registry

This example pulls the latest container image for the `busybox` application and stores the image to a local private docker registry.

----
$ skopeo --insecure-policy copy --src-tls-verify=false --multi-arch=all \
   docker://myZotRegistry.com:5000/busybox:latest \
   docker://localhost:5000/busybox:latest
----

=== Authentication

In these examples, authentication is disabled for the source and destination. You can enable authentication by changing the command line options as follows:

----
--src-tls-verify=true
--dest-tls-verify=true
----

You can also add credentials for authenticating with a source or destination repository:
----

--src-creds username:password
--dest-creds username:password
----
