== Common tasks with regclient

https://github.com/regclient/regclient[regclient] is a client interface that performs various operations on OCI container images and image repositories.  The command line interface for regclient is `regctl.`

NOTE: For detailed information about `regctl` commands, see the https://github.com/regclient/regclient/blob/main/docs/regctl.md[regctl Documentation].


=== Push an OCI image

This example pushes version 1.18 of `golang` to a `tools` repository within the registry.

----
$ regctl registry set --tls=disabled myZotRegistry.com:5000
$ regctl image copy ocidir://path/to/golang:1.18 myZotRegistry.com:5000/tools
----

=== Pull an OCI image

This example pulls version 1.18 of `golang` to a local OCI-layout directory.

----
$ regctl image copy myZotRegistry.com:5000/tools ocidir://path/to/golang:1.18
----

=== List all repositories in registry

This example list all repositories in the registry.

----
$ regctl repo ls myZotRegistry.com:5000
----

=== List tags

This example lists all tags in the `tools` repository within the registry.

----
$ regctl tag ls myZotRegistry.com:5000/tools
----

=== Pull and push manifest

This example pulls and pushes the manifest in the `tools` repository within the registry.

----
$ regctl manifest get myZotRegistry.com:5000/tools --format=raw-body
$ regctl manifest put myZotRegistry.com:5000/tools:1.0.0 \
--format oci --content-type application/vnd.oci.image.manifest.v1+json \
--format oci
----

=== Authentication

In the preceding examples, TLS authentication with the zot registry was disabled by the following command:

----
$ regctl registry set --tls=disabled myZotRegistry.com:5000
----

This command allows `regctl` to accept an HTTP response from the zot server. If TLS authentication is enabled on the zot registry server, you can omit this command from your `regctl` session. 
