== Building {zotLowerName} from Source


=== Supported Platforms

{zotUpperName} is officially supported on `Linux` and `Apple MacOS` platforms. However,
development should be possible on any platform that supports the `golang` toolchain.

=== Prerequisites

==== Install golang (1.17+)

The zot project requires `golang 1.17` or newer. You can follow
https://go.dev/learn/[these instructions] to install the `golang` toolchain.  After
installation, make sure that the `path` environment variable or your IDE can find
the toolchain.

=== Cloning {zotLowerName}

You can download or clone the full {zotLowerName} project from GitHub at
https://github.com/project-zot/zot[project-zot].
To clone the {zotLowerName} project, use this command:

----
$ git clone https://github.com/project-zot/zot.git
----

=== Building zot

To build {zotLowerName}, execute the `make` command in the {zotLowerName} directory
using the following general syntax:

``$ make OS=_os_ ARCH=_architecture_ {binary | binary-minimal}``

The `binary` option builds the full {zotLowerName} binary with all extensions. +
The `binary-minimal` option builds the minimal {zotLowerName} binary without extensions.

Extensions include functions such as:

- metrics
- synchronization
- search
- scrub

==== Examples

The following are examples of the `make` command for several supported platforms
and architectures:

- Linux/Intel-based platforms
+
----
$ make OS=linux ARCH=amd64 binary
----

- Linux/amd64 platform
+
----
$ make OS=linux ARCH=amd64 binary
----

- Linux/ARM64-based platforms such as ARM64 servers and Raspberry Pi4
+
----
$ make OS=linux ARCH=arm64 binary
----

- Apple MacOS/Intel-based platforms
+
----
$ make OS=darwin ARCH=amd64 binary
----

- Apple MacOS/ARM64-based platforms
+
----
$ make OS=darwin ARCH=arm64 binary
----

After running `make`, you can find the resulting executable file in the
`zot/bin` directory.

NOTE: The filename of the executable file will reflect the build options.
For example, a linux build will result in a file named
`zot-darwin-amd64.` For convenience, you can rename the file to simply `zot.`

=== Additional Details

For detailed instructions, see the _{zotUpperName} Developers Guide_ on the GitHub
https://github.com/project-zot/docs-zot[docs-zot] page.
