== What is zli?

zli is a binary that implements a set of command line commands for interacting
with the zot registry server.

== How to Get zli

The zli project is hosted on GitHub at https://github.com/project-zot/zot[project-zot].
From GitHub, you can download the zli binary or you can build zli from the source.

=== Supported Platforms

`zli` is supported for the following operating systems and platform architectures:

[#supported-platforms-and-architectures-table-zli]
.Supported Platforms and Architectures
[%autowidth]
|===
| OS | ARCH | Platform

| linux | amd64 | Intel-based Linux servers
| linux | arm64 | ARM-based servers and Raspberry Pi4
| darwin | amd64 | Intel-based MacOS
| darwin | arm64 | ARM-based MacOS
|===

=== Downloading zli Binaries

Download the executable binary for your server platform and architecture under
"Assets" on the GitHub
https://github.com/project-zot/zot/releases[zot releases] page.

The binary image is named using the platform and architecture from the
 <<supported-platforms-and-architectures-table-zli, Supported Platforms and Architectures>>
 table.  For example, the binary for an Intel-based MacOS server is
 `zli-darwin-amd64.`

=== Building zli from Source

To build the zli binary, copy or clone the {zotLowerName} project from GitHub
and execute the `make cli` command in the zot directory.
Use the same command options that you used to build zot, as shown:

``$ make OS=_os_ ARCH=_architecture_ cli``

For example, the following command builds zli for an Intel-based MacOS server:

----
$ make OS=darwin ARCH=amd64 cli
----

In this example, the resulting executable file is `zli-darwin-amd64` in the
zot/bin directory.


== Common Tasks Using zli

This section includes a few examples of common zot server tasks using the `zli`
command line interface.

[TIP]
====
The instructions and examples in this guide use `zli` as the name of the executable file.

The original filename of the executable file will reflect the build options, such as
`zli-linux-amd64.` For convenience, you can rename the executable to simply `zli.`
====


=== Adding a zot server URL

You can modify the zot server configuration using the <<#_zli-config, `zli config add`>> command.
This example adds a zot server URL with an alias of "remote-zot":

----
$ bin/zli config add remote-zot https://server-example:8080
----

Use the <<#_zli-config, `zli config`>> command to list all configured URLs with their aliases:

----
$ bin/zli config -l
remote-zot   https://server-example:8080
local        http://localhost:8080
----

=== Listing images

You can list all images hosted on a zot server using the <<#_zli-images, `zli images`>> command with
the server's alias:

----
$ bin/zli images remote-zot

IMAGE NAME        TAG               DIGEST    SIZE
postgres          9.6.18-alpine     ef27f3e1  14.4MB
postgres          9.5-alpine        264450a7  14.4MB
busybox           latest            414aeb86  707.8KB
----

You can also filter the image list to view a specific image by specifying the
image name:

----
$ bin/zli images remote-zot -n busybox

IMAGE NAME        TAG               DIGEST    SIZE
busybox           latest            414aeb86  707.8KB
----

=== Scanning images for known vulnerabilities

Using the <<#_zli-cve, `zli cve`>> command, you can fetch the CVE (Common Vulnerabilities and
Exposures) information for images hosted on the zot server. This example shows
how to learn which images are affected by a specific CVE:
----
$ bin/zli cve remote-zot -i CVE-2017-9935

IMAGE NAME        TAG               DIGEST    SIZE
c3/openjdk-dev    commit-5be4d92    ac3762e2  335MB
----

This example displays a list all CVEs affecting a specific image:

----
$ bin/zli cve remote-zot -I c3/openjdk-dev:0.3.19

ID                SEVERITY  TITLE
CVE-2015-8540     LOW       libpng: underflow read in png_check_keyword()
CVE-2017-16826    LOW       binutils: Invalid memory access in the coff_s...
----

This example displays the detailed CVEs in JSON format:

----
$ bin/zli cve remote-zot -I c3/openjdk-dev:0.3.19 -o json
{
  "Tag": "0.3.19",
  "CVEList": [
    {
      "Id": "CVE-2019-17006",
      "Severity": "MEDIUM",
      "Title": "nss: Check length of inputs for cryptographic primitives",
      "Description": "A vulnerability was discovered in nss where input text length was not checked when using certain cryptographic primitives. This could lead to a heap-buffer overflow resulting in a crash and data leak. The highest threat is to confidentiality and integrity of data as well as system availability.",
      "PackageList": [
        {
          "Name": "nss",
          "InstalledVersion": "3.44.0-7.el7_7",
          "FixedVersion": "Not Specified"
        },
        {
          "Name": "nss-sysinit",
          "InstalledVersion": "3.44.0-7.el7_7",
          "FixedVersion": "Not Specified"
        },
        {
          "Name": "nss-tools",
          "InstalledVersion": "3.44.0-7.el7_7",
          "FixedVersion": "Not Specified"
        }
      ]
    }
----

This example lists all images on a specific zot server that are affected by
a specific CVE:

----
$ bin/zli cve remote-zot -I c3/openjdk-dev -i CVE-2017-9935

IMAGE NAME        TAG               DIGEST    SIZE
c3/openjdk-dev    commit-2674e8a    71046748  338MB
c3/openjdk-dev    commit-bd5cc94    0ab7fc76
----

This example lists all images on a specific zot server where the CVE has been fixed:

----
$ bin/zli cve remote-zot -I c3/openjdk-dev -i CVE-2017-9935 --fixed

IMAGE NAME        TAG                       DIGEST    SIZE
c3/openjdk-dev    commit-2674e8a-squashfs   b545b8ba  321MB
c3/openjdk-dev    commit-d5024ec-squashfs   cd45f8cf  321MB
----
