[#_metrics_config]
== Metrics

The available methods for collecting metrics varies depending on whether your {zotLowerName}
installation is the minimal (distribution-spec-only) build or the full build including extensions.

=== Collecting metrics using a node exporter

The minimal {zotLowerName} installation exposes internal metrics in a Prometheus format
through a node exporter. The configuration of the node exporter contains connection
details for the {zotLowerName} server from which it will scrape metrics. Metrics
are automatically enabled in the {zotLowerName} server upon first scrape from the
node exporter.  No extra configuration option is needed. Similarly, the metrics
are automatically disabled when the node exporter has not performed any scrapings
for some period.

=== Enabling metrics for {zotLowerName}

Add the `metrics` attribute under `extensions` in the configuration file
to enable and configure metrics, as shown in the following example.

----
"extensions": {
    "metrics": {
        "enable": true,
        "prometheus": {
            "path": "/metrics"
        }
    }
}
----

The following table lists the configurable attributes for metrics collection.

[%autowidth]
|===
| Attribute | Description

| `enable` |
If this attribute is missing, metrics collection is enabled by default.
Metrics collection can be disabled by setting this attribute to `false`.
| `prometheus` |
Attributes under `prometheus` contain configuration settings for the Prometheus 
node exporter.
| `path` |
The server path on which metrics will be exposed.
|===

.MIKE'S QUESTIONS
****
. Are these the only attributes?
. What additional info do we need about prometheus, etc?
. Do we need a chapter about zxp?
****
