== What is {zotLowerName}?

> Zot is a production-ready, open-source, vendor-neutral container image registry
server based purely on OCI standards.

Two broad trends are changing how we build, distribute, and consume software.
The first trend is the increasing adoption of container technologies. The second trend is
that software solutions are being composed by combining elements from various sources
rather than being built entirely from scratch. The latter trend raises the importance of
software provenance and supply chain security. In both trends, {zotLowerName} intends
to play an important role by providing a production-ready, open-source, vendor-neutral
container image registry server based purely on OCI standards.

=== What is an OCI image registry?

An OCI image registry is a server-based application that allows you to store, manage,
and share container images.  A developer uploads (pushes) an image to the registry for
distribution. Users can then download (pull) the image to run on their systems.  The
https://github.com/opencontainers/distribution-spec[OCI Distribution Specification],
published by the Open Container Initiative (OCI),
defines a standard API protocol for these and other image registry operations.

An image registry can be a part of your continuous integration and continuous
deployment (CI/CD) pipeline when you host {zotLowerName} on your public or
private server. In its minimal form, you can also embed a {zotLowerName} registry
in a product.  In either case, {zotLowerName} provides a secure
software supply chain for container images.
