== Identity-based authorization

User identity can be used as an authorization criterion for allowing actions on
one or more repository paths.  For specific users, you can choose to allow any
combination of read, create, update, or delete actions on specific paths.

For defining policies for specific repository paths, the paths can be specified
explicitly or by using `glob` patterns with simple or recursive wildcards.
When a repository path matches more than one path description, authorization
is granted based on the policy of the longest (most specific) path matched.  For
example, if policies are defined for path descriptions *pass:[**]* and `repos2/repo,`
the `repos2/repo` path will match both *pass:[**]* and `repos2/repo` descriptions.
In this case, the `repos2/repo` policy will be applied because it is longer.

Note that *pass:[**]* effectively defines the default policy, as it matches any path
not matched by any other per-repository policy. To override all other policies,
you can specify a global admin policy.

Use the `accessControl` attribute in the configuration file to define a set of
identity-based authorization policies, as shown in the following example.

[source,json]
----
"accessControl": {
  "**": {
    "policies": [{
      "users": ["charlie"],
      "actions": ["read", "create", "update"]
    }],
    "defaultPolicy": ["read", "create"]
  },
  "tmp/**": {
    "defaultPolicy": ["read", "create", "update"]
  },
  "infra/*": {
    "policies": [{
        "users": ["alice", "bob"],
        "actions": ["create", "read", "update", "delete"]
      },
      {
        "users": ["mallory"],
        "actions": ["create", "read"]
      }
    ],
    "defaultPolicy": ["read"]
  },
  "repos2/repo": {
    "policies": [{
        "users": ["bob"],
        "actions": ["read", "create"]
      },
      {
        "users": ["mallory"],
        "actions": ["create", "read"]
      }
    ],
    "defaultPolicy": ["read"]
  },
  "adminPolicy": {
    "users": ["admin"],
    "actions": ["read", "create", "update", "delete"]
  }
}
----

In this example, five policies are defined:

- The default policy (*pass:[**]*) gives all users the ability to
read or create content, while giving user "charlie" the additional ability to
update content.

- The policy for `pass:[tmp/**]` matches all repositories under `tmp` recursively
and allows all users to read, create, or update content in those repositories.

- The policy for `pass:[infra/*]` matches all repositories directly under `infra.`
Separate policies are defined for specific users, along with a default
read-only policy for all other users.

- The policy for `repos2/repo` matches only that specific repository.

- An admin policy (`adminPolicy`) gives the user "admin" global authorization to
read, create, update, or delete content in any repository, overriding all other
policies.

NOTE: Always include the read action in any policy that you define.  The create,
update, and delete actions cannot be used without the read action.
