[#_metrics_config]
== Metrics

The available methods for collecting metrics varies depending on whether your {zotLowerName}
installation is a minimal (distribution-spec-only) image or a full image including extensions.

=== Enabling metrics for a full {zotLowerName} image with extensions

Add the `metrics` attribute under `extensions` in the configuration file
to enable and configure metrics, as shown in the following example.

----
"extensions": {
    "metrics": {
        "enable": true,
        "prometheus": {
            "path": "/metrics"
        }
    }
}
----

The following table lists the configurable attributes for metrics collection.

[%autowidth]
|===
| Attribute | Description

| `enable` |
If this attribute is missing, metrics collection is enabled by default.
Metrics collection can be disabled by setting this attribute to `false`.
| `prometheus` |
Attributes under `prometheus` contain configuration settings for the Prometheus
node exporter.
| `path` |
The server path on which metrics will be exposed.
|===

=== Collecting metrics from a minimal {zotLowerName} image using a node exporter

Although a minimal {zotLowerName} image does not contain a node exporter, it
exposes internal metrics in a Prometheus format for collection by a separate
node exporter tool such as zxp. The {zotLowerName} companion binary zxp
is a node exporter that can be deployed with a minimal {zotLowerName} image in
order to scrape metrics from the {zotLowerName} server.

Metrics are automatically enabled in the {zotLowerName} server upon first scrape
from the node exporter and the metrics are automatically disabled when the node
exporter has not performed any scraping for some period. No extra {zotLowerName}
configuration is needed for this behavior.

You can download the zxp executable binary for your server platform and
architecture under "Assets" on the GitHub
https://github.com/project-zot/zot/releases[zot releases] page.

The binary image is named using the target platform and architecture. For example,
the binary for an Intel-based MacOS server is
`zxp-darwin-amd64`.  To configure the zxp example image, run this command:

``*zxp-darwin-amd64* *config* _zxp-config-file_``

TIP: For convenience, you can rename the binary image file to simply `zxp.`

TIP: A sample Dockerfile for zxp is available at
https://github.com/project-zot/zot/blob/main/Dockerfile-zxp[Dockerfile-zxp].

The configuration file of zxp contains connection details for the {zotLowerName}
server from which it will scrape metrics. The following JSON structure is an example
of the `_zxp-config-file_` contents:

----
{
    "Server": {
        "protocol": "http",
        "host": "127.0.0.1",
        "port": "8080"
    },
    "Exporter": {
        "port": "8081",
        "log": {
            "level": "debug"
        }
    }
}
----

[TIP]
====
The zxp module does not have Prometheus integration.

The zxp module is not needed with a full {zotLowerName} image.
====
